# Generated by Django 3.1.3 on 2020-12-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicantship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('mailbox', models.EmailField(max_length=254)),
                ('captchaContent', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageContent', models.CharField(max_length=1000)),
                ('messageType', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('publishTime', models.DateTimeField(auto_now_add=True)),
                ('applicationEndTime', models.DateTimeField()),
                ('executionStartTime', models.DateTimeField()),
                ('executionEndTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=200)),
                ('tele', models.CharField(max_length=200)),
                ('passwordAfterMD5', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reporteeship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Receivership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='MissionChannelship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.channel')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.mission')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='applicants',
            field=models.ManyToManyField(related_name='missionsAsApplicant', through='backend.Applicantship', to='backend.User'),
        ),
        migrations.AddField(
            model_name='mission',
            name='members',
            field=models.ManyToManyField(related_name='missionsAsMember', through='backend.Membership', to='backend.User'),
        ),
        migrations.AddField(
            model_name='mission',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missionsAsPublisher', to='backend.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagesAsPublisher', to='backend.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='recievers',
            field=models.ManyToManyField(related_name='messagesAsReciever', through='backend.Receivership', to='backend.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='reportees',
            field=models.ManyToManyField(related_name='messagesAsReportee', through='backend.Reporteeship', to='backend.User'),
        ),
        migrations.AddField(
            model_name='membership',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.mission'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluationScore', models.FloatField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluationsAsEvaluatee', to='backend.user')),
                ('evaluater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluationsAsEvaluater', to='backend.user')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluationsOfTheMission', to='backend.mission')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='missions',
            field=models.ManyToManyField(related_name='channels', through='backend.MissionChannelship', to='backend.Mission'),
        ),
        migrations.AddField(
            model_name='applicantship',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.mission'),
        ),
        migrations.AddField(
            model_name='applicantship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
