# Generated by Django 3.1.3 on 2020-12-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recievers',
        ),
        migrations.AddField(
            model_name='message',
            name='receivers',
            field=models.ManyToManyField(related_name='messagesAsReceiver', through='backend.Receivership', to='backend.User'),
        ),
    ]
